### ISSUE TITLE
求解惑：远程组件this的指向

### ISSUE THREAD

**Issue by jiayechao** [yuzhanglong/mf-lite#38]
我们的技术栈时vue，我们的远程模块A项目使用了一些挂载在vue.prototype上的方法，还有全局的自定义指令，router等等，现在要在另一个项目B上使用，this实例就变成了B。这种情况如何解决？

**Comment by yuzhanglong** [comment]
为什么 B 要用 A 的方法？既然是两个微应用他们应该是相互隔离的，他们最多一起消费基座的方法，要不然很奇怪。

**Comment by jiayechao** [comment]
> 

嗯嗯，因为模块是写在A项目中，当时没有要给别的项目使用的打算，所以耦合了A项目的一些方法，比如vue.prototype.$isApp，现在通过mf暴漏出来给B项目使用，模块中的this指向了B项目的vue.prototype，其中并没有$isApp，导致报错。

**Comment by yuzhanglong** [comment]
你的 A 项目和 B 项目他们的地位是一样的吧（都是子应用）？

**Comment by jiayechao** [comment]
> 你的 A 项目和 B 项目他们的地位是一样的吧（都是子应用）
目前来说，B项目会在以后抽离成算基座项目

**Comment by jiayechao** [comment]
> 我觉得这样搞比较优雅：
> 
> 1. 把 A 项目的这些公共方法抽离到基座项目。
> 2. 将这些方法 expose 出去（文章里面有提到怎么搞）
> 3. 子应用 A 和子应用 B 一起消费这些方法。

嗯嗯，这种最优雅，就是工作量有点大。看来是要逐步分解来改造。
谢谢大佬解惑！
