### ISSUE TITLE
新建模版报错，这个和node的版本有关吗？

### ISSUE THREAD

**Issue by ryanmans** [yuzhanglong/mf-lite#4]
/usr/local/lib/node_modules/@mf-lite/cli/node_modules/npm-check-updates/lib/index.js:428
  throw err
  ^

Error: Command failed with ENOENT: plop --plopfile /usr/local/lib/node_modules/@mf-lite/cli/node_modules/@attachments/assets/lib/configurations/node-plop/micro-fe-generator.js
spawn plop ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn plop',
  path: 'plop',
  spawnargs: [
    '--plopfile',
    '/usr/local/lib/node_modules/@mf-lite/cli/node_modules/@attachments/assets/lib/configurations/node-plop/micro-fe-generator.js'
  ],
  originalMessage: 'spawn plop ENOENT',
  shortMessage: 'Command failed with ENOENT: plop --plopfile /usr/local/lib/node_modules/@mf-lite/cli/node_modules/@attachments/assets/lib/configurations/node-plop/micro-fe-generator.js\n' +
    'spawn plop ENOENT',

**Comment by yuzhanglong** [comment]
应该是项目的依赖问题，我尝试修复下。

**Comment by yuzhanglong** [comment]
临时解决方案：npm install -g plop

**Comment by yuzhanglong** [comment]
已在 v0.1.5 版本中修复这个问题~
