### ISSUE TITLE
同一个文件夹下创建基座和子应用，运行后无法加载子应用

### ISSUE THREAD

**Issue by ZXHHHH123** [yuzhanglong/mf-lite#5]
你好: 
按照文档进行[「安装、执行项目」](https://ph3xmz5sya.feishu.cn/docs/doccnGEPiy8D3DJTZw6S05QJW4f#PhC9Qp)步骤时出现报错，帮忙有空的时候看下什么问题， 多谢～
运行localhost:10000 展示了报错如下图:
![image](https://user-images.githubusercontent.com/23452655/144989370-d6ff487d-ceba-40e8-8f39-e0c76dcd21c2.png)

版本: 
webpack: 5.65.0
webpack-cli: 4.9.1

**Comment by yuzhanglong** [comment]
子应用暂时不支持单独运行，需要在基座环境下运行。

**Comment by ZXHHHH123** [comment]
「基座环境下运行」指的是子应用需要在基座文件夹下mf-lite create 吗？

**Comment by yuzhanglong** [comment]
> 「基座环境下运行」指的是子应用需要在基座文件夹下mf-lite create 吗？

没有必要，他们各自独立的，完全可以在不同的 git 仓库。

**Comment by ZXHHHH123** [comment]
运行起来是这个效果，console正常，大概会是哪的问题呢？
![image](https://user-images.githubusercontent.com/23452655/144993367-d75569dc-e1b3-409f-878c-4ee04aeea102.png)

**Comment by yuzhanglong** [comment]
> 运行起来是这个效果，console正常，大概会是哪的问题呢？ ![image](https://user-images.githubusercontent.com/23452655/144993367-d75569dc-e1b3-409f-878c-4ee04aeea102.png)

子应用跑起来了吗

**Comment by ZXHHHH123** [comment]
主子应用 看起来都是正常run了，并未修改端口

![image](https://user-images.githubusercontent.com/23452655/144995218-56f9a1a4-0181-4c39-a9a3-1171b0de01c6.png)

**Comment by yuzhanglong** [comment]
> 还有几个疑问:
> 
> 1. 后面会考虑子应用单独运行吗？
> 2. 子应用模版目前是只支持react吗？是否会考虑Vue模版
>    （不过如果 子应用只能在基座环境下运行的话  Vue模版就显得没那么重要了）

1. 子应用单独运行感觉不是很有必要（因为子应用某些东西需要消费基座，例如共享的组件库、全局变量、样式。所以子应用能单独跑意义不大）。
我个人觉得**子应用的独立开发**才是刚需，通过代理工具来实现**不开基座的情况下启动子应用，且开发体验和一般的方式别无二致**（已经支持，见文档）

2. 支持，webpack module-federation 特性和 react 不是强耦合 。

**Comment by yuzhanglong** [comment]
> 主子应用 看起来都是正常run了，并未修改端口
> 
> ![image](https://user-images.githubusercontent.com/23452655/144995218-56f9a1a4-0181-4c39-a9a3-1171b0de01c6.png)

我这边试了下项目初始化过程，没有问题，你要不重新走一遍试试？

**Comment by yuzhanglong** [comment]
> > 主子应用 看起来都是正常run了，并未修改端口
> > ![image](https://user-images.githubusercontent.com/23452655/144995218-56f9a1a4-0181-4c39-a9a3-1171b0de01c6.png)
> 
> 我这边试了下项目初始化过程，没有问题，你要不重新走一遍试试？

@ZXHHHH123 同学，现在可以正常运行了吗

**Comment by ZXHHHH123** [comment]
> 
我试了 只有基座名字为base app 才能正常运行 换做其他名字就无法加载了(不好意思 才回复)

**Comment by yuzhanglong** [comment]
> > 
> 
> 我试了 只有基座名字为base app 才能正常运行 换做其他名字就无法加载了(不好意思 才回复)

微应用对应地配置一下基座 app 就行了。因为微应用依赖基座的一些东西，比如 react，如下图：
![image](https://user-images.githubusercontent.com/56540811/145186436-f4f9957a-7851-4a3f-a88c-50bc2962c5d4.png)

**Comment by ZXHHHH123** [comment]
> > > 
> > 
> > 
> > 我试了 只有基座名字为base app 才能正常运行 换做其他名字就无法加载了(不好意思 才回复)
> 
> 微应用对应地配置一下基座 app 就行了。因为微应用依赖基座的一些东西，比如 react，如下图： ![image](https://user-images.githubusercontent.com/56540811/145186436-f4f9957a-7851-4a3f-a88c-50bc2962c5d4.png)
嗯嗯 可以了 多谢

**Comment by yuzhanglong** [comment]
> 修改了base_app为基座应用名，虽然基座应用内嵌子应用是正常运行的，但是直接打开子应用：localhost:10000，还是会报错： ![image](https://user-images.githubusercontent.com/17596583/165046845-4a6d3a80-1dc7-4893-afc5-d649563f6413.png)

上面已经提到这个问题了，不支持子应用单独运行：因为感觉不是很有必要（因为子应用某些东西需要消费基座，例如共享的组件库、全局变量、样式。所以子应用能单独跑意义不大）。

我个人觉得子应用的独立开发才是刚需，通过代理工具来实现不开基座的情况下启动子应用，且开发体验和一般的方式别无二致（已经支持，见文档）

**Comment by zhongshankaka** [comment]
> 

原来是这样，一开始以为子应用只是用了远程的依赖，能独立运行。谢谢。

**Comment by zhongshankaka** [comment]
> > 修改了base_app为基座应用名，虽然基座应用内嵌子应用是正常运行的，但是直接打开子应用：localhost:10000，还是会报错： ![image](https://user-images.githubusercontent.com/17596583/165046845-4a6d3a80-1dc7-4893-afc5-d649563f6413.png)
> 
> 上面已经提到这个问题了，不支持子应用单独运行：因为感觉不是很有必要（因为子应用某些东西需要消费基座，例如共享的组件库、全局变量、样式。所以子应用能单独跑意义不大）。
> 
> 我个人觉得子应用的独立开发才是刚需，通过代理工具来实现不开基座的情况下启动子应用，且开发体验和一般的方式别无二致（已经支持，见文档）

原来是这样，一开始以为子应用只是用了远程的依赖，能独立运行。谢谢。
